title: Milan Thies
description: >-
  Governance of Education and Skills • Labour Markets • Political Economy • Public Administration
url: "https://milanthies.github.io"
theme: minima

# ⬇ Minima-3 settings
minima:
  skin: auto          # light during the day, dark when OS is dark  :contentReference[oaicite:0]{index=0}
  nav_pages:          # what appears in the header bar & in what order  :contentReference[oaicite:1]{index=1}
    - index.md        # Home
    - teaching.md     # Teaching

# Optional social icons (appear top-right)
minima:
  #  … keep skin & nav_pages …
  social_links:
    - { platform: github,  user_url: "https://github.com/milanthies" }
    - { platform: email,   user_url: "mailto:milan.thies@eui.eu" }
